#!/usr/bin/bash

# use -t to configure token
while getopts ":o:h:p:" arg; do
  case $arg in
    o) oldestCommitRevision=$OPTARG;;
    h) headRevision=$OPTARG;;
    p) projectsCommaSeparated=$OPTARG;;
    *) echo "Please provide the oldest and head commits revisions and the projects. usage: $0 [-o -h -p]" >&2
       exit 1 ;;
  esac
done

# Set comma as delimiter
IFS=','
#Read the split projects into an array based on comma delimiter
read -r -a projects <<< "$projectsCommaSeparated"

grepsArguments=""
for project in "${projects[@]}"
do
  grepsArguments="$grepsArguments --grep=\"^$project-[0-9].*\""
done

separator="|"
regex="$( printf "${separator}%s" "${projects[@]}" )"
regex="${regex:${#separator}}"
issueKeys=$(git log "$oldestCommitRevision".."$headRevision" -i --pretty="format:%s""$grepsArguments" | grep -oP --regexp="($regex)-[0-9]{5,6}" | sort -u | tr '\n' ',' | sed 's/,$//g')
echo -e "$issueKeys"